### ISSUE TITLE
pull.rebase false är inte default i git

### ISSUE THREAD

**Issue by viggobergdahl** [lunduniversity/introprog-computer-intro#1]
pull.rebase är inte satt till false som default i git. Ett tillägg i labbhandlingen för hur studenterna löser detta på egen hand vore super! Det lättaste kommandot att köra som jag hittat är 'git config --global pull.rebase false'.

**Comment by mnordahl** [comment]
Efter att ha läst lite om det framstår det som att git ändrade detta beteendet i version 2.27. Numera måste man alltså göra denna inställning, och uttryckligen välja vilken merge strategi man vill använda. Jag ska uppdatera handledningen vid tillfälle.
